spring:
  datasource:
    username: fss
    url: jdbc:h2:mem:fssaccountmanager
    driverClassName: org.h2.Driver
    password: fsskey123
  h2:
    console:
      enabled: 'true'
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info
    org:
      hibernate: error
      springframework:
        web: debug